spring:
  application:
    name: transmitSdk
  profiles:
    active: test

mail:
  debug: true
  smtp:
    ip: 10.138.87.167
    port: 8025
    username: 189690929@qq.com
    password: qtmsjkolxmicbjji
    connectiontimeout: 5000
    timeout: 3000
    ssl:
      enable: false
  freemarker:
    template: /email_template/
filter:
  switch: true
    iplist: 127.0.0.1;10.138.87.167;10.180.96.103